In [1]:
import pandas as pd

In [2]:
# reading in the data
df = pd.read_csv('C:/Users/hp/Desktop/pandas demo/owid_covid_data.csv')

In [3]:
pd.set_option('display.max_columns', 61)
pd.set_option('display.max_rows', 607209,)
# to view all the rows and columns

In [4]:
df.head()
#number of rows and columns

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,excess_mortality,excess_mortality_cumulative,excess_mortality_cumulative_absolute,excess_mortality_cumulative_per_million,hosp_patients,hosp_patients_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,icu_patients,icu_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,stringency_index,reproduction_rate,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,human_development_index
0,Afghanistan,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN
1,Afghanistan,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN
2,Afghanistan,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN
3,Afghanistan,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN
4,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN

In [5]:
df.columns
#column names

Index(['country', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed',
       'total_cases_per_million', 'new_cases_per_million',
       'new_cases_smoothed_per_million', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_deaths_per_million',
       'new_deaths_per_million', 'new_deaths_smoothed_per_million',
       'excess_mortality', 'excess_mortality_cumulative',
       'excess_mortality_cumulative_absolute',
       'excess_mortality_cumulative_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'icu_patients',
       'icu_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'stringency_index',
       'reproduction_rate', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'code', 'continent',
       'population', 'population_density', 'median_age', 'life_expectancy',
       'gdp_per_capita', 'extreme_poverty', 'diabetes_prevalence',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'human_development_index'],
      dtype='object')

In [6]:
df.dtypes
#data types of various columns

country                                        object
date                                           object
total_cases                                   float64
new_cases                                     float64
new_cases_smoothed                            float64
total_cases_per_million                       float64
new_cases_per_million                         float64
new_cases_smoothed_per_million                float64
total_deaths                                  float64
new_deaths                                    float64
new_deaths_smoothed                           float64
total_deaths_per_million                      float64
new_deaths_per_million                        float64
new_deaths_smoothed_per_million               float64
excess_mortality                              float64
excess_mortality_cumulative                   float64
excess_mortality_cumulative_absolute          float64
excess_mortality_cumulative_per_million       float64
hosp_patients                                 float64
hosp_patients_per_million                     float64
weekly_hosp_admissions                        float64
weekly_hosp_admissions_per_million            float64
icu_patients                                  float64
icu_patients_per_million                      float64
weekly_icu_admissions                         float64
weekly_icu_admissions_per_million             float64
stringency_index                              float64
reproduction_rate                             float64
total_tests                                   float64
new_tests                                     float64
total_tests_per_thousand                      float64
new_tests_per_thousand                        float64
new_tests_smoothed                            float64
new_tests_smoothed_per_thousand               float64
positive_rate                                 float64
tests_per_case                                float64
total_vaccinations                            float64
people_vaccinated                             float64
people_fully_vaccinated                       float64
total_boosters                                float64
new_vaccinations                              float64
new_vaccinations_smoothed                     float64
total_vaccinations_per_hundred                float64
people_vaccinated_per_hundred                 float64
people_fully_vaccinated_per_hundred           float64
total_boosters_per_hundred                    float64
new_vaccinations_smoothed_per_million         float64
new_people_vaccinated_smoothed                float64
new_people_vaccinated_smoothed_per_hundred    float64
code                                           object
continent                                      object
population                                    float64
population_density                            float64
median_age                                    float64
life_expectancy                               float64
gdp_per_capita                                float64
extreme_poverty                               float64
diabetes_prevalence                           float64
handwashing_facilities                        float64
hospital_beds_per_thousand                    float64
human_development_index                       float64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607209 entries, 0 to 607208
Data columns (total 61 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   country                                     607209 non-null  object
 1   date                                        607209 non-null  object
 2   total_cases                                 594861 non-null  float64
 3   new_cases                                   590333 non-null  float64
 4   new_cases_smoothed                          589124 non-null  float64
 5   total_cases_per_million                     594861 non-null  float64
 6   new_cases_per_million                       590333 non-null  float64
 7   new_cases_smoothed_per_million              589124 non-null  float64
 8   total_deaths                                594861 non-null  float64
 9   new_deaths                                  591505 non-null  float64
 10  new_deaths_smoothed                         590293 non-null  float64
 11  total_deaths_per_million                    594861 non-null  float64
 12  new_deaths_per_million                      591505 non-null  float64
 13  new_deaths_smoothed_per_million             590293 non-null  float64
 14  excess_mortality                            13807 non-null   float64
 15  excess_mortality_cumulative                 13807 non-null   float64
 16  excess_mortality_cumulative_absolute        13807 non-null   float64
 17  excess_mortality_cumulative_per_million     13773 non-null   float64
 18  hosp_patients                               40656 non-null   float64
 19  hosp_patients_per_million                   40656 non-null   float64
 20  weekly_hosp_admissions                      24497 non-null   float64
 21  weekly_hosp_admissions_per_million          24497 non-null   float64
 22  icu_patients                                39116 non-null   float64
 23  icu_patients_per_million                    39116 non-null   float64
 24  weekly_icu_admissions                       10993 non-null   float64
 25  weekly_icu_admissions_per_million           10993 non-null   float64
 26  stringency_index                            202760 non-null  float64
 27  reproduction_rate                           185683 non-null  float64
 28  total_tests                                 79387 non-null   float64
 29  new_tests                                   75403 non-null   float64
 30  total_tests_per_thousand                    79387 non-null   float64
 31  new_tests_per_thousand                      75403 non-null   float64
 32  new_tests_smoothed                          103965 non-null  float64
 33  new_tests_smoothed_per_thousand             103965 non-null  float64
 34  positive_rate                               101560 non-null  float64
 35  tests_per_case                              100650 non-null  float64
 36  total_vaccinations                          83222 non-null   float64
 37  people_vaccinated                           79011 non-null   float64
 38  people_fully_vaccinated                     77011 non-null   float64
 39  total_boosters                              58784 non-null   float64
 40  new_vaccinations                            68876 non-null   float64
 41  new_vaccinations_smoothed                   202840 non-null  float64
 42  total_vaccinations_per_hundred              83222 non-null   float64
 43  people_vaccinated_per_hundred               79011 non-null   float64
 44  people_fully_vaccinated_per_hundred         77011 non-null   float64
 45  total_boosters_per_hundred                  58784 non-null   float64
 46  new_vaccinations_smoothed_per_million       202840 non-null  float64
 47  new_people_vaccinated_smoothed              202840 non-null  float64
 48  new_people_vaccinated_smoothed_per_hundred  202840 non-null  float64
 49  code                                        581753 non-null  object
 50  continent                                   562641 non-null  object
 51  population                                  588872 non-null  float64
 52  population_density                          579313 non-null  float64
 53  median_age                                  581705 non-null  float64
 54  life_expectancy                             584094 non-null  float64
 55  gdp_per_capita                              487123 non-null  float64
 56  extreme_poverty                             389991 non-null  float64
 57  diabetes_prevalence                         511037 non-null  float64
 58  handwashing_facilities                      295308 non-null  float64
 59  hospital_beds_per_thousand                  413768 non-null  float64
 60  human_development_index                     0 non-null       float64
dtypes: float64(57), object(4)
memory usage: 282.6+ MB

In [8]:
#data usage
df.memory_usage()

Index                                             132
country                                       4857672
date                                          4857672
total_cases                                   4857672
new_cases                                     4857672
new_cases_smoothed                            4857672
total_cases_per_million                       4857672
new_cases_per_million                         4857672
new_cases_smoothed_per_million                4857672
total_deaths                                  4857672
new_deaths                                    4857672
new_deaths_smoothed                           4857672
total_deaths_per_million                      4857672
new_deaths_per_million                        4857672
new_deaths_smoothed_per_million               4857672
excess_mortality                              4857672
excess_mortality_cumulative                   4857672
excess_mortality_cumulative_absolute          4857672
excess_mortality_cumulative_per_million       4857672
hosp_patients                                 4857672
hosp_patients_per_million                     4857672
weekly_hosp_admissions                        4857672
weekly_hosp_admissions_per_million            4857672
icu_patients                                  4857672
icu_patients_per_million                      4857672
weekly_icu_admissions                         4857672
weekly_icu_admissions_per_million             4857672
stringency_index                              4857672
reproduction_rate                             4857672
total_tests                                   4857672
new_tests                                     4857672
total_tests_per_thousand                      4857672
new_tests_per_thousand                        4857672
new_tests_smoothed                            4857672
new_tests_smoothed_per_thousand               4857672
positive_rate                                 4857672
tests_per_case                                4857672
total_vaccinations                            4857672
people_vaccinated                             4857672
people_fully_vaccinated                       4857672
total_boosters                                4857672
new_vaccinations                              4857672
new_vaccinations_smoothed                     4857672
total_vaccinations_per_hundred                4857672
people_vaccinated_per_hundred                 4857672
people_fully_vaccinated_per_hundred           4857672
total_boosters_per_hundred                    4857672
new_vaccinations_smoothed_per_million         4857672
new_people_vaccinated_smoothed                4857672
new_people_vaccinated_smoothed_per_hundred    4857672
code                                          4857672
continent                                     4857672
population                                    4857672
population_density                            4857672
median_age                                    4857672
life_expectancy                               4857672
gdp_per_capita                                4857672
extreme_poverty                               4857672
diabetes_prevalence                           4857672
handwashing_facilities                        4857672
hospital_beds_per_thousand                    4857672
human_development_index                       4857672
dtype: int64

In [9]:
# number na values in each of the columns
df.isnull().sum()

country                                            0
date                                               0
total_cases                                    12348
new_cases                                      16876
new_cases_smoothed                             18085
total_cases_per_million                        12348
new_cases_per_million                          16876
new_cases_smoothed_per_million                 18085
total_deaths                                   12348
new_deaths                                     15704
new_deaths_smoothed                            16916
total_deaths_per_million                       12348
new_deaths_per_million                         15704
new_deaths_smoothed_per_million                16916
excess_mortality                              593402
excess_mortality_cumulative                   593402
excess_mortality_cumulative_absolute          593402
excess_mortality_cumulative_per_million       593436
hosp_patients                                 566553
hosp_patients_per_million                     566553
weekly_hosp_admissions                        582712
weekly_hosp_admissions_per_million            582712
icu_patients                                  568093
icu_patients_per_million                      568093
weekly_icu_admissions                         596216
weekly_icu_admissions_per_million             596216
stringency_index                              404449
reproduction_rate                             421526
total_tests                                   527822
new_tests                                     531806
total_tests_per_thousand                      527822
new_tests_per_thousand                        531806
new_tests_smoothed                            503244
new_tests_smoothed_per_thousand               503244
positive_rate                                 505649
tests_per_case                                506559
total_vaccinations                            523987
people_vaccinated                             528198
people_fully_vaccinated                       530198
total_boosters                                548425
new_vaccinations                              538333
new_vaccinations_smoothed                     404369
total_vaccinations_per_hundred                523987
people_vaccinated_per_hundred                 528198
people_fully_vaccinated_per_hundred           530198
total_boosters_per_hundred                    548425
new_vaccinations_smoothed_per_million         404369
new_people_vaccinated_smoothed                404369
new_people_vaccinated_smoothed_per_hundred    404369
code                                           25456
continent                                      44568
population                                     18337
population_density                             27896
median_age                                     25504
life_expectancy                                23115
gdp_per_capita                                120086
extreme_poverty                               217218
diabetes_prevalence                            96172
handwashing_facilities                        311901
hospital_beds_per_thousand                    193441
human_development_index                       607209
dtype: int64

In [10]:
# another way of countng number of na values in each of the columns
df.isna().sum()

country                                            0
date                                               0
total_cases                                    12348
new_cases                                      16876
new_cases_smoothed                             18085
total_cases_per_million                        12348
new_cases_per_million                          16876
new_cases_smoothed_per_million                 18085
total_deaths                                   12348
new_deaths                                     15704
new_deaths_smoothed                            16916
total_deaths_per_million                       12348
new_deaths_per_million                         15704
new_deaths_smoothed_per_million                16916
excess_mortality                              593402
excess_mortality_cumulative                   593402
excess_mortality_cumulative_absolute          593402
excess_mortality_cumulative_per_million       593436
hosp_patients                                 566553
hosp_patients_per_million                     566553
weekly_hosp_admissions                        582712
weekly_hosp_admissions_per_million            582712
icu_patients                                  568093
icu_patients_per_million                      568093
weekly_icu_admissions                         596216
weekly_icu_admissions_per_million             596216
stringency_index                              404449
reproduction_rate                             421526
total_tests                                   527822
new_tests                                     531806
total_tests_per_thousand                      527822
new_tests_per_thousand                        531806
new_tests_smoothed                            503244
new_tests_smoothed_per_thousand               503244
positive_rate                                 505649
tests_per_case                                506559
total_vaccinations                            523987
people_vaccinated                             528198
people_fully_vaccinated                       530198
total_boosters                                548425
new_vaccinations                              538333
new_vaccinations_smoothed                     404369
total_vaccinations_per_hundred                523987
people_vaccinated_per_hundred                 528198
people_fully_vaccinated_per_hundred           530198
total_boosters_per_hundred                    548425
new_vaccinations_smoothed_per_million         404369
new_people_vaccinated_smoothed                404369
new_people_vaccinated_smoothed_per_hundred    404369
code                                           25456
continent                                      44568
population                                     18337
population_density                             27896
median_age                                     25504
life_expectancy                                23115
gdp_per_capita                                120086
extreme_poverty                               217218
diabetes_prevalence                            96172
handwashing_facilities                        311901
hospital_beds_per_thousand                    193441
human_development_index                       607209
dtype: int64

In [11]:
df.isna().sum().idxmax()
#column with the highest missing values

'human_development_index'

In [12]:
#Data cleaning

In [13]:
clean_df = df.copy()

In [14]:
missing_values = clean_df.isna().sum()

In [15]:
missing_percentage = (missing_values/len(clean_df))*100

In [16]:
missing_percentage.sort_values(ascending = False)
#sorting the percentages in descending order

human_development_index                       100.000000
weekly_icu_admissions                          98.189585
weekly_icu_admissions_per_million              98.189585
excess_mortality_cumulative_per_million        97.731753
excess_mortality_cumulative_absolute           97.726154
excess_mortality_cumulative                    97.726154
excess_mortality                               97.726154
weekly_hosp_admissions_per_million             95.965640
weekly_hosp_admissions                         95.965640
icu_patients_per_million                       93.558066
icu_patients                                   93.558066
hosp_patients                                  93.304447
hosp_patients_per_million                      93.304447
total_boosters                                 90.318984
total_boosters_per_hundred                     90.318984
new_vaccinations                               88.656953
new_tests                                      87.582035
new_tests_per_thousand                         87.582035
people_fully_vaccinated                        87.317217
people_fully_vaccinated_per_hundred            87.317217
people_vaccinated                              86.987841
people_vaccinated_per_hundred                  86.987841
total_tests                                    86.925918
total_tests_per_thousand                       86.925918
total_vaccinations_per_hundred                 86.294340
total_vaccinations                             86.294340
tests_per_case                                 83.424159
positive_rate                                  83.274293
new_tests_smoothed                             82.878218
new_tests_smoothed_per_thousand                82.878218
reproduction_rate                              69.420249
stringency_index                               66.607873
new_people_vaccinated_smoothed                 66.594698
new_vaccinations_smoothed_per_million          66.594698
new_vaccinations_smoothed                      66.594698
new_people_vaccinated_smoothed_per_hundred     66.594698
handwashing_facilities                         51.366334
extreme_poverty                                35.773185
hospital_beds_per_thousand                     31.857400
gdp_per_capita                                 19.776716
diabetes_prevalence                            15.838369
continent                                       7.339812
population_density                              4.594135
median_age                                      4.200201
code                                            4.192296
life_expectancy                                 3.806762
population                                      3.019883
new_cases_smoothed_per_million                  2.978381
new_cases_smoothed                              2.978381
new_deaths_smoothed_per_million                 2.785861
new_deaths_smoothed                             2.785861
new_cases                                       2.779274
new_cases_per_million                           2.779274
new_deaths_per_million                          2.586259
new_deaths                                      2.586259
total_cases                                     2.033567
total_cases_per_million                         2.033567
total_deaths                                    2.033567
total_deaths_per_million                        2.033567
date                                            0.000000
country                                         0.000000
dtype: float64

In [17]:
filt = (missing_percentage >= 70)
columns_to_drop = missing_percentage[filt].index
#filting out the columns to drop

In [18]:
# droping out columns with more than 70 percent missing values
clean_df = clean_df.drop(columns = columns_to_drop, errors = 'ignore')

In [19]:
clean_df.shape

(607209, 31)

In [20]:
# checking for duplicated rows
clean_df.duplicated().sum()

np.int64(0)

In [21]:
clean_df.head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand
0,Afghanistan,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35
1,Afghanistan,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35
2,Afghanistan,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35
3,Afghanistan,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35
4,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35

In [22]:
clean_df['date'] =pd.to_datetime(clean_df['date'])
#converting the date column for object to datetime

In [23]:
clean_df['date'].dtype

dtype('<M8[ns]')

In [24]:
clean_df['country'].isnull().sum()
#to see if there are any na values in the country column

np.int64(0)

In [25]:
#how many countries are there in the dataset
clean_df['country'].nunique()

262

In [26]:
# which country appears most often
clean_df['country'].value_counts().idxmax()

'Afghanistan'

In [27]:
# what is the earliest date
clean_df['date'].min()

Timestamp('2020-01-01 00:00:00')

In [28]:
# what is the latest date
clean_df['date'].max()

Timestamp('2026-07-19 00:00:00')

In [29]:
clean_df.columns

Index(['country', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed',
       'total_cases_per_million', 'new_cases_per_million',
       'new_cases_smoothed_per_million', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_deaths_per_million',
       'new_deaths_per_million', 'new_deaths_smoothed_per_million',
       'stringency_index', 'reproduction_rate', 'new_vaccinations_smoothed',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'code', 'continent',
       'population', 'population_density', 'median_age', 'life_expectancy',
       'gdp_per_capita', 'extreme_poverty', 'diabetes_prevalence',
       'handwashing_facilities', 'hospital_beds_per_thousand'],
      dtype='object')

In [30]:
#which continent has the most observations
clean_df['continent'].value_counts().idxmax()

'Africa'

In [31]:
#filtering

In [32]:
#total cases greater than 1000000
high_total_cases = (clean_df['total_cases'] > 1000000)
clean_df.loc[high_total_cases].head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand
2609,Africa,2020-08-08,1011462.0,13641.0,13210.429,714.86520,9.640971,9.336659,25123.0,420.0,401.14285,17.756039,0.296841,0.283513,NaN,NaN,NaN,NaN,NaN,NaN,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN
2610,Africa,2020-08-09,1025330.0,13868.0,12870.429,724.66656,9.801407,9.096359,25539.0,416.0,419.42856,18.050053,0.294014,0.296437,NaN,NaN,NaN,NaN,NaN,NaN,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN
2611,Africa,2020-08-10,1037535.0,12205.0,12648.714,733.29266,8.626058,8.939659,25877.0,338.0,418.14285,18.288939,0.238886,0.295528,NaN,NaN,NaN,NaN,NaN,NaN,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN
2612,Africa,2020-08-11,1045907.0,8372.0,12341.429,739.20966,5.917030,8.722481,26197.0,320.0,419.14285,18.515102,0.226165,0.296235,NaN,NaN,NaN,NaN,NaN,NaN,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN
2613,Africa,2020-08-12,1053556.0,7649.0,12046.143,744.61570,5.406040,8.513783,26457.0,260.0,391.42856,18.698862,0.183759,0.276648,NaN,NaN,NaN,NaN,NaN,NaN,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN

In [33]:
#new cases greater than 50000
high_new_cases = (clean_df['new_cases'] > 50000)
clean_df.loc[high_new_cases].head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand
2945,Africa,2021-07-10,5887830.0,51767.0,40416.570,4161.3076,36.587067,28.564987,150910.0,919.0,769.5714,106.657790,0.649516,0.543906,NaN,NaN,483450.53,335.56460,264817.60,0.018381,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN
2966,Africa,2021-07-31,6699660.0,51179.0,39128.715,4735.0800,36.171490,27.654778,169892.0,878.0,946.5714,120.073590,0.620539,0.669003,NaN,NaN,824466.30,572.26483,593988.60,0.041229,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN
2972,Africa,2021-08-06,6944556.0,64190.0,42296.430,4908.1640,45.367200,29.893604,175876.0,1521.0,980.2857,124.302870,1.074988,0.692831,NaN,NaN,856453.90,594.46747,578276.25,0.040138,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN
2973,Africa,2021-08-07,6995564.0,51008.0,42272.000,4944.2144,36.050632,29.876339,177027.0,1151.0,1019.2857,125.116356,0.813486,0.720395,NaN,NaN,878435.25,609.72480,596508.00,0.041404,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN
2985,Africa,2021-08-19,7440873.0,61657.0,39738.715,5258.9430,43.576965,28.085903,187346.0,1073.0,900.5714,132.409450,0.758358,0.636492,NaN,NaN,1217320.50,844.94620,722601.50,0.050156,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN

In [34]:
#African counties only
filt = clean_df['continent']  == 'Africa'
clean_df.loc[filt].head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand
7173,Algeria,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,DZA,Africa,45477391.0,19.094181,27.983,76.128899,15882.713867,0.0,17.5,84.927719,1.61
7174,Algeria,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,DZA,Africa,45477391.0,19.094181,27.983,76.128899,15882.713867,0.0,17.5,84.927719,1.61
7175,Algeria,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,DZA,Africa,45477391.0,19.094181,27.983,76.128899,15882.713867,0.0,17.5,84.927719,1.61
7176,Algeria,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,DZA,Africa,45477391.0,19.094181,27.983,76.128899,15882.713867,0.0,17.5,84.927719,1.61
7177,Algeria,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,DZA,Africa,45477391.0,19.094181,27.983,76.128899,15882.713867,0.0,17.5,84.927719,1.61

In [35]:
#Ghana only
filt = clean_df['country']  == 'Ghana'
clean_df.loc[filt].head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand
201193,Ghana,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,GHA,Africa,33149152.0,145.689423,20.736,65.246002,7357.833496,39.025792,2.7,45.484077,0.69
201194,Ghana,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,GHA,Africa,33149152.0,145.689423,20.736,65.246002,7357.833496,39.025792,2.7,45.484077,0.69
201195,Ghana,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,GHA,Africa,33149152.0,145.689423,20.736,65.246002,7357.833496,39.025792,2.7,45.484077,0.69
201196,Ghana,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,GHA,Africa,33149152.0,145.689423,20.736,65.246002,7357.833496,39.025792,2.7,45.484077,0.69
201197,Ghana,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,GHA,Africa,33149152.0,145.689423,20.736,65.246002,7357.833496,39.025792,2.7,45.484077,0.69

In [36]:
#Germany only
filt = clean_df['country']  == 'Germany'
clean_df.loc[filt].head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand
198801,Germany,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,DEU,Europe,84086227.0,240.665802,45.023998,80.579597,62823.773438,0.7,7.8,NaN,7.55
198802,Germany,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,DEU,Europe,84086227.0,240.665802,45.023998,80.579597,62823.773438,0.7,7.8,NaN,7.55
198803,Germany,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,DEU,Europe,84086227.0,240.665802,45.023998,80.579597,62823.773438,0.7,7.8,NaN,7.55
198804,Germany,2020-01-04,1.0,1.0,NaN,0.011893,0.011893,NaN,0.0,0.0,NaN,0.000000,0.000000,NaN,0.0,NaN,NaN,NaN,NaN,NaN,DEU,Europe,84086227.0,240.665802,45.023998,80.579597,62823.773438,0.7,7.8,NaN,7.55
198805,Germany,2020-01-05,1.0,0.0,NaN,0.011893,0.000000,NaN,3.0,3.0,NaN,0.035678,0.035678,NaN,0.0,NaN,NaN,NaN,NaN,NaN,DEU,Europe,84086227.0,240.665802,45.023998,80.579597,62823.773438,0.7,7.8,NaN,7.55

In [37]:
#data on 2021 only
filt = clean_df['date']  == '2021'
clean_df.loc[filt].head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand
366,Afghanistan,2021-01-01,52513.0,183.0,131.14285,1294.0979,4.509739,3.231803,2201.0,12.0,9.428572,54.240080,0.295721,0.232352,12.04,0.8575,NaN,NaN,NaN,NaN,AFG,Asia,4.057885e+07,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35
2755,Africa,2021-01-01,2755392.0,29790.0,23036.42800,1947.4126,21.054506,16.281324,65607.0,693.0,580.714300,46.368683,0.489788,0.410428,NaN,NaN,0.0,0.0,0.0,0.0,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN
5147,Albania,2021-01-01,57727.0,581.0,487.14285,20415.4450,205.473590,172.280530,1174.0,4.0,8.142858,415.191040,1.414620,2.879763,56.48,0.9619,NaN,NaN,NaN,NaN,ALB,Europe,2.827614e+06,103.197594,35.943001,78.768799,22724.292969,0.340922,10.6,NaN,2.90
7539,Algeria,2021-01-01,99610.0,299.0,371.85715,2190.3190,6.574696,8.176747,2756.0,5.0,7.285714,60.601543,0.109945,0.160205,72.22,0.7718,NaN,NaN,NaN,NaN,DZA,Africa,4.547739e+07,19.094181,27.983000,76.128899,15882.713867,0.000000,17.5,84.927719,1.61
9928,American Samoa,2021-01-01,0.0,0.0,0.00000,0.0000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,ASM,Oceania,4.836500e+04,241.824997,27.927000,72.752098,NaN,NaN,NaN,NaN,NaN

In [38]:
#data on 2022-01-01 only
filt = clean_df['date']  > '2022-01-01'
clean_df.loc[filt].head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand
732,Afghanistan,2022-01-02,158112.0,53.0,30.000000,3896.4143,1.306099,0.739301,7356.0,0.0,0.571429,181.27672,0.000000,0.014082,19.44,1.3166,17269.479,425.57837,16258.330,0.040066,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35
733,Afghanistan,2022-01-03,158156.0,44.0,29.285715,3897.4985,1.084309,0.721699,7361.0,5.0,1.000000,181.39993,0.123217,0.024643,19.44,1.3281,17603.846,433.81830,16593.309,0.040892,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35
734,Afghanistan,2022-01-04,158171.0,15.0,29.142857,3897.8682,0.369651,0.718179,7364.0,3.0,1.428572,181.47386,0.073930,0.035205,19.44,1.3386,17603.846,433.81830,16593.309,0.040892,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35
735,Afghanistan,2022-01-05,158207.0,36.0,29.857143,3898.7554,0.887162,0.735781,7366.0,2.0,1.571428,181.52315,0.049287,0.038725,19.44,1.3493,17603.846,433.81830,16593.309,0.040892,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35
736,Afghanistan,2022-01-06,158245.0,38.0,29.428572,3899.6920,0.936449,0.725220,7367.0,1.0,1.571428,181.54779,0.024643,0.038725,19.44,1.3601,17603.846,433.81830,16593.309,0.040892,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35

In [39]:
#creating new row called death rate
clean_df['death_rate'] = (clean_df['total_deaths']/clean_df['total_cases'])*1000

In [40]:
clean_df.head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,death_rate
0,Afghanistan,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN
1,Afghanistan,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN
2,Afghanistan,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN
3,Afghanistan,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN
4,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN

In [41]:
#creating new row called recovery estimate
clean_df['recovery_estimate'] = clean_df['total_cases'] - clean_df['total_deaths']

In [42]:
clean_df.head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,death_rate,recovery_estimate
0,Afghanistan,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN,NaN
1,Afghanistan,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN,NaN
2,Afghanistan,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN,NaN
3,Afghanistan,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN,0.0
4,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN,0.0

In [43]:
#creating new row called total cases per million
clean_df['total_cases_per_million'] = clean_df['total_cases']/1000000

In [44]:
#creating new row called new cases per million
clean_df['new_cases_per_million'] = clean_df['new_cases']/1000000

In [45]:
#creating new row called cases per million difference
clean_df['Cases_per_Million_Difference'] = clean_df['total_cases_per_million'] - clean_df['new_cases_per_million']

In [46]:
clean_df.head(  )

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,death_rate,recovery_estimate,Cases_per_Million_Difference
0,Afghanistan,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN,NaN,NaN
1,Afghanistan,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN,NaN,NaN
2,Afghanistan,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN,NaN,NaN
3,Afghanistan,2020-01-04,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN,0.0,0.0
4,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,AFG,Asia,40578847.0,62.215549,16.752001,65.616997,1964.452271,NaN,11.7,51.938343,0.35,NaN,0.0,0.0

In [47]:
#sorting
#top 20 countries with highest total cases
top_total_cases = clean_df.sort_values(by = 'total_cases', ascending = False).drop_duplicates(subset = 'country').head(20)
top_total_cases[['country', 'total_cases']]

                                                  country  total_cases
592862                                              World  779178934.0
595254                                  World excl. China  679797173.0
597643                  World excl. China and South Korea  645225300.0
600027  World excl. China, South Korea, Japan and Sing...  608415573.0
234659                              High-income countries  458049855.0
31075                                                Asia  302204311.0
572194                      Upper-middle-income countries  257538779.0
172500                                             Europe  254960114.0
33465                                    Asia excl. China  202822550.0
174884                                European Union (27)  186984090.0
390585                                      North America  124521655.0
567173                                      United States  103436829.0
109624                                              China   99381761.0
503273                                      South America   69395641.0
310471                      Lower-middle-income countries   60612047.0
245741                                              India   45056221.0
186843                                             France   39060935.0
201127                                            Germany   38437953.0
76517                                              Brazil   38042729.0
504873                                        South Korea   34571873.0

In [48]:
#top 20 countries with highest total deaths
clean_df.dropna()
top_total_deaths = clean_df.sort_values(by = 'total_deaths', ascending = False).drop_duplicates(subset = 'country').head(20)
top_total_deaths[['country', 'total_deaths']]

                                                  country  total_deaths
592864                                              World     7115203.0
595249                                  World excl. China     6992805.0
597643                  World excl. China and South Korea     6956871.0
600030  World excl. China, South Korea, Japan and Sing...     6880153.0
234662                              High-income countries     3504285.0
572194                      Upper-middle-income countries     2768291.0
172496                                             Europe     2111758.0
390581                                      North America     1717393.0
31061                                                Asia     1637901.0
33452                                    Asia excl. China     1515503.0
503271                                      South America     1356693.0
174889                                European Union (27)     1271056.0
567416                                      United States     1238678.0
310433                      Lower-middle-income countries      796035.0
76509                                              Brazil      704045.0
245715                                              India      533849.0
444389                                             Russia      404290.0
342738                                             Mexico      335111.0
4494                                               Africa      258288.0
564464                                     United Kingdom      232112.0

In [49]:
#top 20 countries with highest deaths rate
top_death_rate = clean_df.sort_values(by = 'death_rate', ascending = False).drop_duplicates(subset = 'country').head(20)
top_death_rate[['country', 'death_rate']]

                                                  country  death_rate
604882                                           Zimbabwe         inf
71824                                            Botswana         inf
420725                                               Peru         inf
184585                                             France   1038750.0
333293                                         Mauritania     29800.0
172513                                European Union (27)      3000.0
198815                                            Germany      3000.0
597645  World excl. China, South Korea, Japan and Sing...      3000.0
592869                                  World excl. China      3000.0
170114                                             Europe      3000.0
595256                  World excl. China and South Korea      3000.0
232275                              High-income countries      3000.0
590478                                              World      1500.0
248345                                               Iran      1000.0
512924                                              Sudan      1000.0
562667                                     United Kingdom      1000.0
98117                                      Cayman Islands      1000.0
423084                                        Philippines      1000.0
253142                                            Ireland      1000.0
227562                                             Guyana      1000.0

In [50]:
#top 20 countries with highest deaths rate
top_death_rate = clean_df.sort_values(by = 'death_rate', ascending = True).drop_duplicates(subset = 'country').head(20)
top_death_rate[['country', 'death_rate']]

                       country  death_rate
56                 Afghanistan         0.0
347588                  Monaco         0.0
496188                 Somalia         0.0
498560            South Africa         0.0
350011                Mongolia         0.0
76603   British Virgin Islands         0.0
343624    Micronesia (country)         0.0
503294             South Korea         0.0
78978                   Brunei         0.0
345235                 Moldova         0.0
500947           South America         0.0
74204                   Brazil         0.0
357180                 Morocco         0.0
354833              Montserrat         0.0
359584              Mozambique         0.0
581361                 Vatican         0.0
340435                  Mexico         0.0
81368                 Bulgaria         0.0
581851               Venezuela         0.0
367574                   Nauru         0.0

In [51]:
#grouping

In [52]:
#average cases by each continent
continent_groups = clean_df.groupby(['continent'])
continent_groups['total_cases'].mean()

continent
Africa           1.784830e+05
Asia             4.173668e+06
Europe           3.437695e+06
North America    2.208252e+06
Oceania          3.900702e+05
South America    3.678338e+06
Name: total_cases, dtype: float64

In [53]:
#average deaths by each continent
continent_groups = clean_df.groupby(['continent'])
continent_groups['total_deaths'].mean()

continent
Africa            3671.500030
Asia             26403.534872
Europe           31771.849851
North America    31660.587500
Oceania            831.860646
South America    78295.520840
Name: total_deaths, dtype: float64

In [54]:
#maximum total cases by each continent
continent_groups = clean_df.groupby(['continent'])
continent_groups['total_cases'].max()

continent
Africa             4073188.0
Asia              99381761.0
Europe            39060935.0
North America    103436829.0
Oceania           11861161.0
South America     38042729.0
Name: total_cases, dtype: float64

In [55]:
#maximum deaths by each continent
continent_groups = clean_df.groupby(['continent'])
continent_groups['total_deaths'].max()

continent
Africa            102595.0
Asia              533849.0
Europe            404290.0
North America    1238678.0
Oceania            25236.0
South America     704045.0
Name: total_deaths, dtype: float64

In [56]:
#average life expectancy by each continent
continent_groups = clean_df.groupby(['continent'])
continent_groups['life_expectancy'].mean()

continent
Africa           64.874759
Asia             74.850548
Europe           79.637127
North America    75.855512
Oceania          72.607620
South America    74.823787
Name: life_expectancy, dtype: float64

In [57]:
#average gdp_per_capita by each continent
continent_groups = clean_df.groupby(['continent'])
continent_groups['gdp_per_capita'].mean()

continent
Africa            7125.278000
Asia             29595.367485
Europe           52429.542598
North America    33899.716361
Oceania          14362.461239
South America    26537.800515
Name: gdp_per_capita, dtype: float64

In [58]:
#average gdp_per_capita by each continent
continent_groups = clean_df.groupby(['continent'])
continent_groups[['total_cases', 'total_deaths']].agg(['mean', 'max'])

                total_cases               total_deaths
                       mean          max          mean        max
continent
Africa         1.784830e+05    4073188.0   3671.500030   102595.0
Asia           4.173668e+06   99381761.0  26403.534872   533849.0
Europe         3.437695e+06   39060935.0  31771.849851   404290.0
North America  2.208252e+06  103436829.0  31660.587500  1238678.0
Oceania        3.900702e+05   11861161.0    831.860646    25236.0
South America  3.678338e+06   38042729.0  78295.520840   704045.0

In [59]:
#finding interesting facts

In [60]:
#country with the highest new cases
count_with_hnew_cases = clean_df.sort_values(by = 'new_cases', ascending = False).drop_duplicates(subset = 'country').head()
count_with_hnew_cases[['country', 'new_cases']]

                                                  country  new_cases
591234                                              World  8401906.0
593623                                  World excl. China  8401713.0
596012                  World excl. China and South Korea  8384638.0
598401  World excl. China, South Korea, Japan and Sing...  8295098.0
29773                                                Asia  7213802.0

In [61]:
#country with the highest new cases
highest_new_cases = clean_df.loc[clean_df["new_cases"].idxmax()]
highest_new_cases[["country", "date", "new_cases"]]

country                    World
date         2022-01-30 00:00:00
new_cases              8401906.0
Name: 591234, dtype: object

In [62]:
#country with the highest total deaths
highest_deaths = clean_df.loc[clean_df['total_deaths'].idxmax()]
highest_deaths[["country", "date", "total_deaths"]]

country                       World
date            2026-07-14 00:00:00
total_deaths              7115203.0
Name: 592860, dtype: object

In [63]:
#country with the highest people fully vaccinated
highest_deaths = clean_df.loc[clean_df['new_vaccinations_smoothed'].idxmax()]
highest_deaths[["country", "date", "new_vaccinations_smoothed"]]

country                                    World
date                         2021-06-27 00:00:00
new_vaccinations_smoothed             43691812.0
Name: 591017, dtype: object

In [64]:
#country with the highest stringency index
highest_deaths = clean_df.loc[clean_df['stringency_index'].idxmax()]
highest_deaths[["country", "date", "stringency_index"]]

country                       Argentina
date                2020-03-23 00:00:00
stringency_index                  100.0
Name: 21598, dtype: object

In [65]:
#country with the highest life expectancy
highest_deaths = clean_df.loc[clean_df['life_expectancy'].idxmax()]
highest_deaths[["country", "date", "life_expectancy"]]

country                         Monaco
date               2020-01-01 00:00:00
life_expectancy              85.746399
Name: 347548, dtype: object

In [66]:
# multi-condintioning filtering

In [67]:
filt = (clean_df['continent'] == 'Africa' ) & (clean_df['total_cases'] > 500000)
clean_df.loc[filt].head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,death_rate,recovery_estimate,Cases_per_Million_Difference
152611,Egypt,2022-03-19,500889.0,5516.0,788.0,0.500889,0.005516,6.997089,24361.0,84.0,12.0,216.31485,0.745883,0.106555,39.70,0.2150,276798.70,2457.8490,168517.110,0.149636,EGY,Africa,112618252.0,113.133011,23.813,71.009697,17265.148438,1.373785,22.4,92.305176,1.06,48.635526,476528.0,0.495373
152612,Egypt,2022-03-20,500889.0,0.0,788.0,0.500889,0.000000,6.997089,24361.0,0.0,12.0,216.31485,0.000000,0.106555,39.68,0.2187,274452.90,2437.0198,165177.470,0.146670,EGY,Africa,112618252.0,113.133011,23.813,71.009697,17265.148438,1.373785,22.4,92.305176,1.06,48.635526,476528.0,0.500889
152613,Egypt,2022-03-21,500889.0,0.0,788.0,0.500889,0.000000,6.997089,24361.0,0.0,12.0,216.31485,0.000000,0.106555,39.68,0.2223,259322.95,2302.6726,151205.440,0.134264,EGY,Africa,112618252.0,113.133011,23.813,71.009697,17265.148438,1.373785,22.4,92.305176,1.06,48.635526,476528.0,0.500889
152614,Egypt,2022-03-22,500889.0,0.0,788.0,0.500889,0.000000,6.997089,24361.0,0.0,12.0,216.31485,0.000000,0.106555,39.68,0.2261,244193.00,2168.3252,137233.400,0.121857,EGY,Africa,112618252.0,113.133011,23.813,71.009697,17265.148438,1.373785,22.4,92.305176,1.06,48.635526,476528.0,0.500889
152615,Egypt,2022-03-23,500889.0,0.0,788.0,0.500889,0.000000,6.997089,24361.0,0.0,12.0,216.31485,0.000000,0.106555,39.68,0.2307,231408.80,2054.8071,126601.016,0.112416,EGY,Africa,112618252.0,113.133011,23.813,71.009697,17265.148438,1.373785,22.4,92.305176,1.06,48.635526,476528.0,0.500889

In [68]:
filt = (clean_df['continent'] == 'Europe' ) & (clean_df['death_rate'] > 20)
clean_df.loc[filt].head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,death_rate,recovery_estimate,Cases_per_Million_Difference
4852,Albania,2020-03-12,10.0,8.0,1.428572,0.000010,0.000008,0.505221,1.0,1.0,0.142857,0.353655,0.353655,0.050522,51.85,NaN,NaN,NaN,NaN,NaN,ALB,Europe,2827614.0,103.197594,35.943001,78.768799,22724.292969,0.340922,10.6,NaN,2.9,100.000000,9.0,0.000002
4853,Albania,2020-03-13,15.0,5.0,2.142857,0.000015,0.000005,0.757832,1.0,0.0,0.142857,0.353655,0.000000,0.050522,78.70,NaN,NaN,NaN,NaN,NaN,ALB,Europe,2827614.0,103.197594,35.943001,78.768799,22724.292969,0.340922,10.6,NaN,2.9,66.666667,14.0,0.000010
4854,Albania,2020-03-14,23.0,8.0,3.285714,0.000023,0.000008,1.162009,1.0,0.0,0.142857,0.353655,0.000000,0.050522,78.70,NaN,NaN,NaN,NaN,NaN,ALB,Europe,2827614.0,103.197594,35.943001,78.768799,22724.292969,0.340922,10.6,NaN,2.9,43.478261,22.0,0.000015
4855,Albania,2020-03-15,33.0,10.0,4.714286,0.000033,0.000010,1.667231,1.0,0.0,0.142857,0.353655,0.000000,0.050522,81.48,NaN,NaN,NaN,NaN,NaN,ALB,Europe,2827614.0,103.197594,35.943001,78.768799,22724.292969,0.340922,10.6,NaN,2.9,30.303030,32.0,0.000023
4856,Albania,2020-03-16,38.0,5.0,5.428571,0.000038,0.000005,1.919842,1.0,0.0,0.142857,0.353655,0.000000,0.050522,81.48,NaN,NaN,NaN,NaN,NaN,ALB,Europe,2827614.0,103.197594,35.943001,78.768799,22724.292969,0.340922,10.6,NaN,2.9,26.315789,37.0,0.000033

In [69]:
filt = (clean_df['new_cases'] > 10000 ) & (clean_df['new_deaths'] > 100)
clean_df.loc[filt].head()

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,new_deaths_smoothed,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,stringency_index,reproduction_rate,new_vaccinations_smoothed,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,code,continent,population,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,death_rate,recovery_estimate,Cases_per_Million_Difference
2561,Africa,2020-06-21,295278.0,10345.0,8708.857,0.295278,0.010345,6.155109,9707.0,315.0,302.14285,6.860560,0.222631,0.213544,NaN,NaN,NaN,NaN,NaN,NaN,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN,32.874105,285571.0,0.284933
2565,Africa,2020-06-25,333846.0,11308.0,9558.143,0.333846,0.011308,6.755354,10990.0,375.0,332.57144,7.767339,0.265037,0.235050,NaN,NaN,NaN,NaN,NaN,NaN,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN,32.919370,322856.0,0.322538
2566,Africa,2020-06-26,345748.0,11902.0,9954.714,0.345748,0.011902,7.035636,11269.0,279.0,322.71430,7.964526,0.197187,0.228083,NaN,NaN,NaN,NaN,NaN,NaN,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN,32.593102,334479.0,0.333846
2567,Africa,2020-06-27,357141.0,11393.0,10315.429,0.357141,0.011393,7.290576,11557.0,288.0,309.28570,8.168075,0.203548,0.218592,NaN,NaN,NaN,NaN,NaN,NaN,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN,32.359768,345584.0,0.345748
2568,Africa,2020-06-28,370005.0,12864.0,10675.286,0.370005,0.012864,7.544910,11887.0,330.0,311.42856,8.401307,0.233232,0.220107,NaN,NaN,NaN,NaN,NaN,NaN,OWID_AFR,NaN,1.445863e+09,48.321529,18.893999,62.920502,NaN,NaN,NaN,NaN,NaN,32.126593,358118.0,0.357141

In [70]:
#save

In [71]:
top_countries = clean_df.sort_values(by = 'total_cases', ascending = False).drop_duplicates(subset = 'country').index
clean_df_top_countries = clean_df.loc[top_countries]

In [72]:
#saving the data for top 20 countries with highest total cases
clean_df_top_countries.to_csv('C:/Users/hp/Desktop/pandas demo/top countries.csv')

In [73]:
# filtering out the data on africa
filt = clean_df['continent'] == 'Africa'
africa = clean_df[filt]

In [74]:
#saving the data for only african countries
africa.to_csv('C:/Users/hp/Desktop/pandas demo/africa.csv')

In [75]:
group_country = clean_df.groupby('continent')

In [89]:
summary_cases = group_country.agg(Average_Cases = ("total_cases", "mean"), Average_Deaths = ("total_deaths", "mean"),
Maximum_Cases = ("total_cases", "max"), Maximum_Deaths = ("total_deaths", "max"))

In [90]:
summary_cases.to_csv('C:/Users/hp/Desktop/pandas demo/maximum _cases.csv')